theme: jekyll-theme-cayman
navigation: 
- title: Home
  url: /

- title: About
  url: /about/
  sublinks:
    - title: Imprint
      url: /about/imprint
    - title: Privacy
      url: /about/privacy
