url: https://frdlweb.de
theme:  jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - html-pipeline
  - jekyll-paginate
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
defaults:
  -
    scope:
      path: "/" # an empty string here means all files in the project      
      # type: "frdl"
    values:
      layout: "default"
      sitemap: true
